---
# vars file for vsftpd
ftp_vars:
  - ftp_service: vsftpd
    all_anon: YES
    anon_root: /var/ftp/pub
    local_enable: YES
    write_enable: YES
    local_umask: '022'
    anon_umask: '022'
    dirmessage_enable: YES
    xferlog_enable: YES
    connect_from_port_20: YES
    xferlog_std_format: YES
    listen: YES
    pam_service_name: vsftpd
    userlist_enable: YES
